apiVersion: v1
data:
  relay: |
    exporters:
      debug/override:
        sampling_initial: 2
        sampling_thereafter: 1
        verbosity: basic
      otlphttp/observe/base:
        compression: zstd
        endpoint: https://100112502756.collect.observeinc.com/v2/otel
        headers:
          authorization: ${env:OBSERVE_TOKEN}
        retry_on_failure:
          enabled: true
          initial_interval: 1s
          max_elapsed_time: 5m
          max_interval: 30s
        sending_queue:
          enabled: true
      prometheusremotewrite:
        endpoint: https://100112502756.collect.observeinc.com/v1/prometheus
        headers:
          authorization: ${env:OBSERVE_TOKEN}
        resource_to_telemetry_conversion:
          enabled: true
        send_metadata: true
    extensions:
      file_storage:
        create_directory: true
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
    processors:
      attributes/debug_source_hostmetrics:
        actions:
        - action: insert
          key: debug_source
          value: hostmetrics
      attributes/debug_source_kubletstats_metrics:
        actions:
        - action: insert
          key: debug_source
          value: kubeletstats_metrics
      attributes/debug_source_pod_logs:
        actions:
        - action: insert
          key: debug_source
          value: pod_logs
      batch:
        send_batch_max_size: 4096
        send_batch_size: 4096
      k8sattributes:
        extract:
          metadata:
          - k8s.namespace.name
          - k8s.deployment.name
          - k8s.replicaset.name
          - k8s.statefulset.name
          - k8s.daemonset.name
          - k8s.cronjob.name
          - k8s.job.name
          - k8s.node.name
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.cluster.uid
          - k8s.node.name
          - k8s.node.uid
          - k8s.container.name
          - container.id
        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection
      memory_limiter:
        check_interval: 5s
        limit_percentage: 75
        spike_limit_percentage: 25
      resource/observe_common:
        attributes:
        - action: upsert
          key: k8s.cluster.name
          value: ${env:OBSERVE_CLUSTER_NAME}
        - action: upsert
          key: k8s.cluster.uid
          value: ${env:OBSERVE_CLUSTER_UID}
      resourcedetection/cloud:
        detectors:
        - eks
        - gcp
        - ecs
        - ec2
        - azure
        override: false
        timeout: 2s
    receivers:
      filelog:
        exclude:
        - '**/*.gz'
        - '**/*.tmp'
        exclude_older_than: 24h
        include:
        - /var/log/pods/*/*/*.log
        - /var/log/pods/*/*/*.log.*
        - /var/log/kube-apiserver-audit.log
        include_file_name: false
        include_file_path: true
        operators:
        - id: container-parser
          max_log_size: 102400
          type: container
        retry_on_failure:
          enabled: true
          initial_interval: 1s
          max_elapsed_time: 5m
          max_interval: 30s
        start_at: end
        storage: file_storage
      hostmetrics:
        collection_interval: 60s
        root_path: /hostfs
        scrapers:
          cpu: null
          disk: null
          filesystem:
            exclude_fs_types:
              fs_types:
              - autofs
              - binfmt_misc
              - bpf
              - cgroup2
              - configfs
              - debugfs
              - devpts
              - devtmpfs
              - fusectl
              - hugetlbfs
              - iso9660
              - mqueue
              - nsfs
              - overlay
              - proc
              - procfs
              - pstore
              - rpc_pipefs
              - securityfs
              - selinuxfs
              - squashfs
              - sysfs
              - tracefs
              match_type: strict
            exclude_mount_points:
              match_type: regexp
              mount_points:
              - /dev/*
              - /proc/*
              - /sys/*
              - /run/k3s/containerd/*
              - /var/lib/docker/*
              - /var/lib/kubelet/*
              - /snap/*
          load: null
          memory: null
          network: null
      kubeletstats:
        auth_type: serviceAccount
        collection_interval: 60s
        endpoint: ${env:K8S_NODE_NAME}:10250
        extra_metadata_labels:
        - container.id
        insecure_skip_verify: true
        k8s_api_config:
          auth_type: serviceAccount
        metric_groups:
        - node
        - pod
        - container
        metrics:
          container.cpu.usage:
            enabled: true
          container.cpu.utilization:
            enabled: false
          container.uptime:
            enabled: true
          k8s.container.cpu.node.utilization:
            enabled: true
          k8s.container.cpu_limit_utilization:
            enabled: true
          k8s.container.cpu_request_utilization:
            enabled: true
          k8s.container.memory.node.utilization:
            enabled: true
          k8s.container.memory_limit_utilization:
            enabled: true
          k8s.container.memory_request_utilization:
            enabled: true
          k8s.node.cpu.usage:
            enabled: true
          k8s.node.cpu.utilization:
            enabled: false
          k8s.node.uptime:
            enabled: true
          k8s.pod.cpu.node.utilization:
            enabled: true
          k8s.pod.cpu.usage:
            enabled: true
          k8s.pod.cpu.utilization:
            enabled: false
          k8s.pod.cpu_limit_utilization:
            enabled: true
          k8s.pod.cpu_request_utilization:
            enabled: true
          k8s.pod.memory.node.utilization:
            enabled: true
          k8s.pod.memory_limit_utilization:
            enabled: true
          k8s.pod.memory_request_utilization:
            enabled: true
          k8s.pod.uptime:
            enabled: true
        node: ${env:K8S_NODE_NAME}
    service:
      extensions:
      - health_check
      - file_storage
      pipelines:
        logs:
          exporters:
          - otlphttp/observe/base
          processors:
          - memory_limiter
          - k8sattributes
          - batch
          - resourcedetection/cloud
          - resource/observe_common
          - attributes/debug_source_pod_logs
          receivers:
          - filelog
        metrics/hostmetrics:
          exporters:
          - prometheusremotewrite
          processors:
          - memory_limiter
          - k8sattributes
          - batch
          - resourcedetection/cloud
          - resource/observe_common
          - attributes/debug_source_hostmetrics
          receivers:
          - hostmetrics
        metrics/kubeletstats:
          exporters:
          - prometheusremotewrite
          processors:
          - memory_limiter
          - k8sattributes
          - batch
          - resourcedetection/cloud
          - resource/observe_common
          - attributes/debug_source_kubletstats_metrics
          receivers:
          - kubeletstats
      telemetry:
        logs:
          encoding: console
          level: WARN
        metrics:
          address: ${env:MY_POD_IP}:8888
          level: normal
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: observe-agent
    meta.helm.sh/release-namespace: observe
  creationTimestamp: "2025-01-29T16:49:08Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: node-logs-metrics
  namespace: observe
  resourceVersion: "1477"
  uid: 96d7799f-3c32-4849-94fb-4080a01e094e
