apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: spring-react-app-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/app/opentelemetry-javaagent.jar"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://observe-agent-forwarder.observe.svc.cluster.local:4318"
            - name: OTEL_LOG_LEVEL
              value: "debug"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=spring-react-app,env=luke_dev"