apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-react-app
  template:
    metadata:
      labels:
        app: spring-react-app
    spec:
      containers:
        - name: backend
          image: spring-react-app-backend
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/app/opentelemetry-javaagent.jar"
            - name: OTEL_SERVICE_NAME
              value: "spring-react-app-backend"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://observe-agent-forwarder.observe.svc.cluster.local:4318"
            - name: OTEL_LOG_LEVEL
              value: "debug"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=spring-react-app,env=production"
          ports:
            - containerPort: 8080
        - name: frontend
          image: spring-react-app-frontend
          imagePullPolicy: IfNotPresent
          env:
            - name: OTEL_SERVICE_NAME
              value: "spring-react-app-frontend"
          ports:
            - containerPort: 80