apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend # must match your backend deployment's label
  ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 80
      #nodePort: 30000  # Access frontend on Minikube

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend  # must match your backend deployment's label
  ports:
    - name: backend
      protocol: TCP
      port: 8080
      targetPort: 8080