application:
  prometheusScrape:
    enabled: false
cluster:
  name: observe-agent-monitored-cluster
node:
  containers:
    logs:
      enabled: true
observe:
  collectionEndpoint:
    value: https://100112502756.collect.observeinc.com/
